### PR TITLE
Issue-30: Enhancement - Create hockey-elo-tracker iOS project

### PR DESCRIPTION
**Pull request by dnjhnsn52**
#### Description

Adds iOS started project with RxSwift redux and cocoapods

#### Technical Details
Adds seed iOS project to build out a Elo-tracker user mobile app.

### CODE REVIEW

**Comment by aturingmachine** [comment]
I know nothing of iOS development so I will trust you on this lol.

**Comment by dnjhnsn52** [comment]
@aturingmachine I can move it into /app that is cool.

**Comment by aturingmachine** [comment]
After discussion about our kiosk solution is it reasonable to close this PR without merging?

**Comment by dnjhnsn52** [comment]
I think that I may just go with it and pivot this to create an app with stats and such for the users.

**Comment by aturingmachine** [comment]
Cool, I will approve then. We will need to get a new directory for the kiosk app.

**Pull request merged**
